# Disable specific rules you don't want to enforce
disabled_rules:
  - force_cast
  - force_try

# Opt-in rules for additional checks
opt_in_rules:
  - empty_count
  - explicit_init

# Line length constraints
line_length:
  warning: 160
  error: 200
  
trailing_whitespace:
  severity: warning
  ignores_empty_lines: false

opening_brace:
  ignore_multiline_statement_conditions: true
  ignore_multiline_function_signatures: true

# Function body length checks
function_body_length:
  warning: 80
  error: 120

# Custom rule for TODO comments (corrected format)
#custom_rules:
#  no_todos:
#    included: "*.swift"
#    name: "No TODO comments"
#    regex: "TODO:"
#    message: "TODO comments should be removed."
#    severity: warning

# Include specific files or directories for linting
included:
  - Earthquakes
  - EarthquakesTest
  - Preview\ Content

# Exclude specific files or directories from linting
excluded:
  - Today/Pods
  - Pods
  - Carthage
